# filepath: c:\Users\Lenovo\Desktop\MGA\tasks\migrations\0002_rename_title_task_name.py
# Generated by Django 5.2 on 2025-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]