# filepath: c:\Users\Lenovo\Desktop\MGA\tasks\migrations\0003_rename_change_date_taskhistory_changed_at_and_more.py
# Generated by Django 5.2 on 2025-06-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_title_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='change_date',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='change_type',
            new_name='changes',
        ),
    ]